all:
	gcc tcpserver.c -o tcpserver
	gcc tcpclient.c -o tcpclient
	gcc udpserver.c -o udpserver
	gcc udpclient.c -o udpclient

tcp:
	gcc tcpserver.c -o tcpserver
	gcc tcpclient.c -o tcpclient

udp:
	gcc udpserver.c -o udpserver
	gcc udpclient.c -o udpclient

clean:
	rm tcpserver tcpclient udpserver udpclient