all:
	gcc tcpserver.c -o tcpserver
	gcc tcpclient1.c -o tcpclient1
	gcc tcpclient2.c -o tcpclient2
	gcc udpserver.c -o udpserver
	gcc udpclient1.c -o udpclient1
	gcc udpclient2.c -o udpclient2

tcp:
	gcc tcpserver.c -o tcpserver
	gcc tcpclient1.c -o tcpclient1
	gcc tcpclient2.c -o tcpclient2

udp:
	gcc udpserver.c -o udpserver
	gcc udpclient1.c -o udpclient1
	gcc udpclient2.c -o udpclient2

clean:
	rm tcpserver tcpclient1 tcpclient2 udpserver udpclient1 udpclient2